import fs from 'fs';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { OpenAPIV2, OpenAPIV3, OpenAPIV3_1 } from 'openapi-types';
import path from 'path';
import prettier from 'prettier';

import { ParsedTool, parseOpenApi } from './parser';

type IsActionsEnabledOpt = Array<string> | ((actionName: string) => boolean);

type ActionConfig = Partial<{
  title: string;
  description: string;
  normalizer: (args: any) => any;
}>;

const isActionsEnabled = (isActionsEnabledOpt: IsActionsEnabledOpt, actionName: string) => {
  if (typeof isActionsEnabledOpt === 'function') {
    return isActionsEnabledOpt(actionName);
  }
  return isActionsEnabledOpt.includes(actionName);
};

const generateToolInputFromParsedTool = (tool: ParsedTool) => {
  const mergedSchema = JSON.parse(JSON.stringify(tool.inputSchema));
  mergedSchema.properties = {
    ...mergedSchema.properties,
    ...tool.pathParamsSchema?.properties,
    ...tool.queryParamsSchema?.properties,
  };
  mergedSchema.required = [
    ...mergedSchema.required,
    ...(tool.pathParamsSchema?.required ?? []),
    ...(tool.queryParamsSchema?.required ?? []),
  ];

  return `${jsonSchemaToZod(mergedSchema)}.shape`;
};

type CodegenOpts = {
  path?: string;
  document: OpenAPIV3_1.Document | OpenAPIV3.Document | OpenAPIV2.Document;
  isActionsEnabled?: IsActionsEnabledOpt;
  actions?: Record<string, ActionConfig>;
};

export const codegen = async (opts: CodegenOpts) => {
  const { document, path: outputPath } = opts;

  const tools = parseOpenApi(document.paths ?? {});

  const runtime = fs.readFileSync(path.join(import.meta.dirname, 'runtime.ts'), 'utf8');

  let output: string = `
    /**
     * This file is auto-generated by yarn generate:mcp-tools
     * DO NOT EDIT THIS FILE MANUALLY
     */
  
      import { z } from "zod";
      import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

      ${runtime}\n

      export const setupTools = (server: McpServer, opts: OpenAPIToolRuntimeConfigOpts) => {

      const config = new OpenAPIToolRuntimeConfig(opts);

    `;

  tools.forEach((tool) => {
    if (opts.isActionsEnabled && !isActionsEnabled(opts.isActionsEnabled, tool.name)) {
      return;
    }

    // Derive MCP tool annotations from the HTTP method: GET/HEAD are read-only,
    // DELETE is destructive. A human-friendly title can be supplied via opts.actions.
    const method = tool.method.toUpperCase();
    const annotations: Record<string, any> = {
      readOnlyHint: method === 'GET' || method === 'HEAD',
      destructiveHint: method === 'DELETE',
    };

    const actionTitle = opts.actions?.[tool.name]?.title;
    if (actionTitle) {
      annotations.title = actionTitle;
    }

    const description = opts.actions?.[tool.name]?.description ?? tool.description;

    const toolArgs = [`"${tool.name}"`, `"${description}"`, generateToolInputFromParsedTool(tool)];

    // annotations always carry read-only/destructive hints, so always include them
    toolArgs.push(JSON.stringify(annotations));

    toolArgs.push(`async (args) => {
            return await config.executeToolCall({
                name: "${tool.name}",
                path: "${tool.path}",
                method: "${tool.method.toUpperCase()}",
                input: args,
                pathParamKeys: ${
                  tool.pathParamsSchema
                    ? `[${Object.keys(tool.pathParamsSchema.properties ?? {})
                        .map((r) => `"${r}"`)
                        .join(',')}]`
                    : '[]'
                },
                queryParamKeys: ${
                  tool.queryParamsSchema
                    ? `[${Object.keys(tool.queryParamsSchema.properties ?? {})
                        .map((r) => `"${r}"`)
                        .join(',')}]`
                    : '[]'
                },
              });
        }`);

    output += `server.tool(${toolArgs.join(',')});\n`;
  });

  output += `
    }
    `;

  const formattedOutput = await prettier.format(output, { parser: 'typescript' });

  if (outputPath) {
    fs.writeFileSync(outputPath, formattedOutput);
  }

  return formattedOutput;
};
